:

# $ FIRST_NAME='___' LAST_NAME='___' TOWN='___' COUNTRY='Germany' EMAIL_ADDRESS='___' PHONE_NUMBE='+49___' ~/git-servers/github.com/JochenHayek/misc/shell/create_vcf.sh | tee ~/transfer--DEFINITELY_NON-PERMANENT/___.vcf
# $ FIRST_NAME='___' LAST_NAME='___' TOWN='___' COUNTRY='Germany' EMAIL_ADDRESS='___' PHONE_NUMBE='+49___' ~/bin/create_vcf.sh | tee ~/transfer--DEFINITELY_NON-PERMANENT/___.vcf

cat <<EOF
BEGIN:VCARD
VERSION:3.0
FN;CHARSET=UTF-8: ${FIRST_NAME} ${LAST_NAME}
N;CHARSET=UTF-8:${LAST_NAME};${FIRST_NAME}
NICKNAME;CHARSET=UTF-8:
EMAIL;CHARSET=UTF-8;INTERNET:${EMAIL_ADDRESS}
TEL;TYPE=WORK,VOICE:${PHONE_NUMBE}
ADR;CHARSET=UTF-8;TYPE=WORK:;;;${TOWN};;;${COUNTRY}
ORG;CHARSET=UTF-8:
NOTE;CHARSET=UTF-8:

END:VCARD
EOF
