#!/usr/bin/perl

# $Id: JHpath_clean 1.4 1995/05/22 06:41:16 hayek Exp $
# $Source: /Users/johayek/git-servers/github.com/JochenHayek/misc/path/RCS/JHpath_clean $
# Time-stamp: <95/05/22 08:40:31 hayek>

# Usage: JHpath_clean path_value
#     where `path_value' is any value like $PATH,
#     that is of the form `a:b:c'

# in:

# out:

# requirements:

{
  $debug = 1;
  
  local(@splitted_path_value);
  local(%set_of_dir);

  local($elem);
  foreach $elem (split(/:/,$ARGV[0]))
    {
      if (defined($set_of_dir{$elem}))
	{
	  # eliminate duplicates
	}
      elsif (-d $elem)
	{
	  $set_of_dir{$elem} = 1;
	  push(@splitted_path_value,$elem);
	}
      else
	{
	  # eliminate non-existing directories,
	  # ..., non-directories, ...
	}
    }

  print join(':',@splitted_path_value),"\n";
}
