#!/usr/bin/perl

# Usage: JHpath_delete path_value dir

# in:
#     `path_value' is any value like $PATH,
#         that is of the form `a:b:c'
#     `dir' ...

# out:
#   eliminated `dir' from `path_value'

# requirements:

{
  $debug = 1;
  
  my(@split_path_value);

  my($elem);
  foreach $elem (split(/:/,$ARGV[0]))
    {
      if($elem eq $ARGV[1])
	{
	  # don't want this directory in the path
	  next;
	}
      else
	{
	  push(@split_path_value,$elem);
	}
    }

  print join(':',@split_path_value),"\n";
}
