#!/usr/bin/perl -w

# $Id: JHdiary 1.12 1997/02/19 10:24:27 jhayek Exp $
# $Source: /Users/johayek/git-servers/github.com/JochenHayek/misc/diary/RCS/JHdiary $
# Time-stamp: <97/02/19 11:22:59 jhayek>

# Usage: 

# in:

# out:

# requirements:

{
  $debug   = 1;
  # $p_do_it = 1;
  $p_echo_the_source = 1;

  die "I need at least the company tag." if $#ARGV < 0;

  local($company_tag) = shift;

  if (0)
    {
      # described in:
      #		camel book / ch. 7: the std. perl lib. / lib. modules / Getopt::Long - ...

      use Getopt::Long;
      %options = ();

      local($result) =
	&GetOptions
	  (\%options
	   ,'columns=i'			# 1..3
	   ,'landscape','portrait'	# 
	   ,'font_size=i'		# 6,12,24
	   ,'no_header'			# pr(1)'s `-t'
	   ,'offset=i'			# pr(1)'s `-o'
	   );

      $result || die 'GetOptions failed';
    }

  %month_name2no =
    ( 'Jan', 1,'Feb', 2,'Mar', 3
     ,'Apr', 4,'May', 5,'Jun', 6
     ,'Jul', 7,'Aug', 8,'Sep', 9
     ,'Oct',10,'Nov',11,'Dec',12
     );

  local($total_work_min) = 0;
  local($total_work_mm);
  local($total_work_hh);

  open(TBL,">$ENV{'HOME'}/diary.month-tbl") || die "cannot open month tbl: $! -";

  while (<>)
    {
      chop;

      local($other_tags);

      if (m/^(\d\d) (\w\w\w) (\d\d\d\d)/)
	{
	  $this_day     = $_;
	  $day_of_month = $1;
	  $month        = $month_name2no{$2};
	  $year         = $3;

	  if (0 && $debug)
	    {
	      printf STDERR "=%d: %s=>'%s',%s=>%d\n",__LINE__
		,'$this_day',$this_day
		,'$day_of_month',$day_of_month
		;
	    }

	  print $_,"\n" if $p_echo_the_source;
	}

      elsif (m/^\t(\d\d):(\d\d) \.\. (\d\d):(\d\d)=(\w\w):(\w\w)=(\w\w):(\w\w)\+(\d\d):(\d\d)--S:\w\w\w:\w\w\((\w\w\w)\) \[work\@$company_tag((,)(.+))?\]$/)
	{
	  local($start_hh,$start_mm) = ( $1, $2); local($start_min) = $start_hh * 60 + $start_mm;
	  local($end_hh  ,$end_mm  ) = ( $3, $4); local($end_min  ) = $end_hh   * 60 + $end_mm;
	  local($total_hh,$total_mm) = ( $5, $6);
	  local($work_hh ,$work_mm ) = ( $7, $8);
	  local($break_hh,$break_mm) = ( $9,$10);
	  local($target_hhh        ) = ($11    );
	  local($other_tags_dummy,$other_tags_separator,$other_tags) = ($12,$13,$14);
	  local($other_tags_alt_separator);

	  if(defined($other_tags_dummy))
	    {
	      $other_tags_alt_separator = '|';
	    }
	  else
	    {
	      $other_tags_dummy         = '';
	      $other_tags_alt_separator = '';
	      $other_tags_separator 	= '';
	      $other_tags           	= '';
	    }

	  local($total_min__computed) = $end_min - $start_min;

	  if ("$total_hh:$total_mm" eq 'hh:mm') # concerns `total' time
	    {
	    }
	  else
	    {
	      local($total_min) = $total_hh * 60 + $total_mm;

	      if ($total_min__computed != $total_min)
		{
		  printf STDERR "=%d: %s=>%d,%s=>%d,%s=>%d\n",__LINE__
		    ,'$.',$.
		    ,'$total_min__computed',$total_min__computed
		    ,'$total_min'          ,$total_min
		    ;
		  warn "manual computing is not that easy ... - sum";
		}
	    }

	  local($total_min) = $total_min__computed;

	  local($ctotal_mm) =  $total_min               % 60;
	  local($ctotal_hh) = ($total_min - $ctotal_mm) / 60;

	  local($break_min)  = $break_hh  * 60 + $break_mm;

	  local($work_min__computed) = $total_min__computed - $break_min;

	  if ("$work_hh:$work_mm" eq 'hh:mm') # concerns `work' time
	    {
	    }
	  else
	    {
	      local($work_min)   = $work_hh   * 60 + $work_mm ;

	      if  (($work_min+$break_min) != $total_min)
		{
		  printf STDERR "=%d: %s=>%d,%s=>%d,%s=>%d,%s=>%d\n",__LINE__
		    ,'$.',$.
		    ,'$work_min' ,$work_min
		    ,'$break_min',$break_min
		    ,'$total_min',$total_min
		    ;
		  warn "manual computing is not that easy ... - sum-break";
		}
	    }

	  local($work_min) = $work_min__computed;

	  local($cwork_mm) =  $work_min             % 60;
	  local($cwork_hh) = ($work_min - $cwork_mm) / 60;

	  $total_work_min += $work_min;
	  $total_work_mm =  $total_work_min                   % 60;
	  $total_work_hh = ($total_work_min - $total_work_mm) / 60;

	  printf STDERR
	    "%04.4d-%02.2d-%02.2d|%02.2d:%02.2d|%02.2d:%02.2d|%02.2d:%02.2d|%02.2d:%02.2d|%4.4d|%s%s%s\n"
	    ,$year,$month,$day_of_month
	    ,$start_hh,$start_mm,$end_hh ,$end_mm
	    ,$ctotal_hh,$ctotal_mm
	    ,$cwork_hh,$cwork_mm,$work_min
	    ,$this_day
	    ,$other_tags_alt_separator
	    ,$other_tags
	    ;

	  printf TBL
	    "%04.4d-%02.2d-%02.2d|%02.2d:%02.2d|%02.2d:%02.2d|%02.2d:%02.2d|%02.2d:%02.2d|%4.4d%s%s\n"
	    ,$year,$month,$day_of_month
	    ,$start_hh,$start_mm,$end_hh ,$end_mm
	    ,$ctotal_hh,$ctotal_mm
	    ,$cwork_hh,$cwork_mm,$work_min
	    ,$other_tags_alt_separator
	    ,$other_tags
	    ;
	  printf        "\t%02.2d:%02.2d .. %02.2d:%02.2d=%02.2d:%02.2d=%02.2d:%02.2d+%02.2d:%02.2d--S:%03.3d:%02.2d(%s) [%s%s]\n"
	    ,$start_hh,$start_mm,$end_hh ,$end_mm
	    ,$ctotal_hh,$ctotal_mm,$cwork_hh,$cwork_mm
	    ,$break_hh,$break_mm
	    ,$total_work_hh,$total_work_mm
	    ,$target_hhh
	    ,"work\@${company_tag}"
	    ,$other_tags_dummy
	    if $p_echo_the_source;
	}

      elsif (m/^\t\w\w:\w\w \.\. \w\w:\w\w=(\w\w):(\w\w)=(\w\w):(\w\w)\+\d\d:\d\d--S:\w\w\w:\m\m\(\w\w\w\) \[work\@$company_tag(,.+)?\]$/)
	{
	  print $_,"\n" if $p_echo_the_source;
	}

      elsif (m/work\@$company_tag/)
	{
	  printf STDERR "=%d: %s=>%d,%s=>'%s' // %s\n",__LINE__
	    ,'$.',$.
	    ,'$_',$_
	    ,"mysteriously matching [work\@${company_tag}]"
	    ;
	  print $_,"\n" if $p_echo_the_source;
	}
      else
	{
	  print $_,"\n" if $p_echo_the_source;
	}
    }

  if (1)
    {
      printf STDERR "=%d: %s=>%04.4d,%s=>%03.3d:%02.2d\n",__LINE__
	,'$total_work_min',$total_work_min
	,'$total_work_{hh,mm}' ,$total_work_hh,$total_work_mm
	;
      printf TBL
	"=\n*||||%02.2d:%02.2d|%4.4d|*\n"
	,$total_work_hh,$total_work_mm,$total_work_min
	;
      printf TBL ".\\\" =%d: %s=>%04.4d,%s=>%03.3d,%s=>%02.2d // %03.3d:%02.2d\n",__LINE__
	,'$total_work_min',$total_work_min
	,'$total_work_hh' ,$total_work_hh
	,'$total_work_mm' ,$total_work_mm
	,$total_work_hh
	,$total_work_mm
	if 0;
    }

  close(TBL);
}
