# ...

all:
	@echo "*** what to do?"
	@echo "	make clean"
	@echo "	make create_test_files_0"
	@echo "	make create_test_files_1"
	@echo "	make run_test"

clean:
	-$(RM) -f 999990-*.{png,jpg,pdf}

create_test_files_0:
	touch image2017-08-30-190215.pdf image2017-08-30-185638-1.jpg image2017-08-30-185638-20.jpg

run_test:
	$${HOME}/Computers/Software/Operating_Systems/Unix/Shell/lexmark-scanner-rename.sh
