# ...

all:
	@echo "*** what to do?"
	@echo "	make clean"
	@echo "	make create_test_files"
	@echo "	make run_test"

clean:
	-$(RM) 999990-*.pdf

create_test_files:
	touch 31.12.13_23.59_Telefax.03021479879.pdf 26.05.13_08.00_Telefax.033202700199.pdf

run_test:
	$${HOME}/Computers/Software/Operating_Systems/Unix/Shell/Telefax-rename.sh
